
## Energieperspektiven 2050+ des Bundes {#sec-ep2050plus}

Die dargestellten Ausbauziele orientieren sich an den Energieperspektiven 2050+ (EP2050+), Szenario ZERO-Basis des Bundes [@ep2050plus]. In den EP2050+ werden insgesamt fünf Szenarien untersucht: (i) Weiter wie bisher (WWB) (ii) ZERO-Basis, (iii) ZERO-A, (iv) ZERO-B und (iv) ZERO-C. Alle "ZERO"-Szenarien führen zu Netto-Null Emissionen im Jahr 2050, jedoch basierend auf unterschiedlichen Technologieschwerpunkten. In diesem Bericht wird das Szenario ZERO-Basis verwendet, weil es für den Kanton Luzern aktuell das realistischste Szenario darstellt. ZERO-Basis zeichnet sich durch eine hohe Kosteneffizienz, eine hohe gesellschaftliche Akzeptanz, eine hohe energetische Versorgungssicherheit und durch seine Robustheit bezüglich der Zielerreichung aus. Der Fokus liegt bei diesem Szenario auf Energieeffizienz, Elektrifizierung des Verkehrs und der Wärme (Raumwärme) und dem Ausbau thermischer Netze. Biogene Brenn- und Treibstoffe sowie Wasserstoff und darauf aufbauende synthetische Energieträger werden zudem wichtig sein, um Hochtemperaturprozesse in der Industrie, die Spitzenlastabdeckung bei Fernwärmenetzen, Segmente des schweren Güterverkehrs und den internationalen Flugverkehr zu dekarbonisieren. Zusätzlich werden Technologien eingesetzt, um CO~2~-Emissionen aus der Atmosphäre zu entfernen (Carbon Capture and Storage [CCS] oder Negativemissionstechnologien [NET])[^ep2050PlusSzenarien]. 

[^ep2050PlusSzenarien]: Die Szenarien ZERO-A, ZERO-B, und ZERO-C legen ein grösseres Gewicht auf Elektrifizierung (ZERO-A), Biogas, synthetische Gase, Wasserstoff (ZERO-B) bzw. Wärmenetze, flüssige biogene und synthetische Treibstoffe (ZERO-C) im Vergleich zu ZERO-Basis.
Die für diesen Bericht verwendeten Daten der Energieperspektiven 2050+ sind als Excel-Datei online publiziert [@ep2050plusTabellen]. Für diesen Bericht wurden folgende Arbeitsblätter dieser Excel-Datei verwendet: Bruttoenergieverbrauch (03 BEV), Endenergieverbrauch (04 EEV), Stromverbrauch (05 Elektrizität), Endverbrauch erneuerbarer Energien (07 Erneuerbare Energien), Wärmeverbrauch (11 Wärme), Stromverbrauch der Wärmepumpen (12 Wärmepumpen) und Stromerzeugung (19 Energiewirtschaft).